# Generated by Django 4.2.1 on 2023-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('home_address', models.CharField(max_length=32)),
                ('order_history', models.JSONField()),
                ('payment_method', models.CharField(max_length=32)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
