# Generated by Django 3.2.12 on 2023-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=140582688129264, upload_to='images/'),
            preserve_default=False,
        ),
    ]
