# Generated by Django 4.2.1 on 2023-06-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=4)),
                ('currency', models.DecimalField(decimal_places=4, max_digits=4)),
                ('date_of_payment', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
