# Generated by Django 4.2.1 on 2023-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews_and_Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('review_Content', models.CharField(max_length=32)),
                ('rating', models.IntegerField()),
                ('cumulative_ratings', models.IntegerField()),
                ('author', models.CharField(max_length=32)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
