# Generated by Django 4.2.1 on 2023-06-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32)),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=4)),
                ('delivery_address', models.CharField(max_length=32)),
                ('contact_number', models.CharField(max_length=32)),
                ('payment_status', models.BooleanField()),
                ('items', models.JSONField()),
                ('order_status', models.BooleanField()),
                ('payment_method', models.CharField(max_length=32)),
            ],
        ),
    ]
