# Generated by Django 3.2.12 on 2023-07-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('product_cart', '0002_product_cart_products'),
        ('delivery', '0001_initial'),
        ('orders', '0002_remove_order_items_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_cart.product_cart'),
        ),
    ]
